### ISSUE TITLE
呜呜呜~~连不上 Cloudflare 服务器呢~~

### ISSUE THREAD

**Issue by cnmeeia** [GenshinMinecraft/Cloudflare-Workers-Ai-Telegram-Bot#2]
呜呜呜~~连不上 Cloudflare 服务器呢~~

**Comment by GenshinMinecraft** [comment]
字面意思，还有该项目基本停止开发，逐渐转向 Rust 版本，请前往

https://github.com/GenshinMinecraft/Rust-Cloudflare-Workers-AI-Telegram-Bot
